### ISSUE TITLE
Clicking Slick in search returns wrong item

### ISSUE THREAD

**Issue by ckhawks** [illogicalNetwork/Tarkov-Changes-Issues#1]
![image](https://user-images.githubusercontent.com/4939600/145880415-6effccc7-e9a9-4c8f-939a-a54536ddc189.png)
Clicking on the Black slick in search results returns a page which has wrong item title

Page is correct (http://tarkov-changes.com/item/LBT-6094A%20Slick%20Plate%20Carrier), but it has `(Olive)` in the item title when it shouldn't

**Comment by ghost** [comment]
Fixed - thanks @ckhawks !

**Comment by ghost** [comment]
https://tarkov-changes.com/item/LBT-6094A%20Slick%20Plate%20Carrier
