### ISSUE TITLE
Flash drive is not listed properly

### ISSUE THREAD

**Issue by ckhawks** [illogicalNetwork/Tarkov-Changes-Issues#11]
None of the links go to normal flash drives

![image](https://user-images.githubusercontent.com/4939600/145895025-dbb4940c-2e40-459a-bf51-f2d79d0ceb76.png)

**Comment by ghost** [comment]
I can't seem to repro. All of items here go to their respective item pages.

**Comment by ckhawks** [comment]
These three pages have the same item ID of Item ID 590c62a386f77412b0130255
https://tarkov-changes.com/item/Sliderkey%20Secure%20Flash%20drive  
https://tarkov-changes.com/item/Sliderkey%20Flash%20drive
https://tarkov-changes.com/item/Secure%20Flash%20drive - this page reads Sliderkey Secure Flash Drive when it shouldn't; it also says Not exist for item rarity which is not true; this spawns in the world and it spawns in containers

**Comment by ghost** [comment]
@ckhawks yes indeed, sorry about that. Should be fixed now!
