### ISSUE TITLE
Bug: some Previous Changes cause the page to nest itself

### ISSUE THREAD

**Issue by wlechowicz** [illogicalNetwork/Tarkov-Changes-Issues#12]
Clicking on some entries in Previous Changes causes the page to nest inside itself. See below.
One entry near the top that does this currently is https://tarkov-changes.com/changelogs/old/output-1214211.txt
That's because rather than returning and handling an error (for whatever is wrong with the resource), you return the home page instead.
Side note - not a great idea to return a full-fledged html page for a .txt resource (working resources return a text/plain content, this is text/html instead).

Clicking this one:
![obraz](https://user-images.githubusercontent.com/24250766/146454616-36aaff80-02a7-4a03-b94d-53e18bcf677d.png)

Causes this to happen:
![obraz](https://user-images.githubusercontent.com/24250766/146454690-0a5139bd-9cb4-49be-b865-151f9b84b51b.png)

**Comment by RatherLogical** [comment]
Appreciate the bug report. This is due to a quirk with the backend nginx configuration. I'll get with our backend team and get this sorted.

**Comment by LogicalSoIutions** [comment]
This won't happen anymore as long as I don't brain derp :)

**Comment by wlechowicz** [comment]
> as long as I don't brain derp

Not going to take that long 😄 Cheers!
