### ISSUE TITLE
Glorious E wrong and not full info

### ISSUE THREAD

**Issue by VeryGooDiS** [illogicalNetwork/Tarkov-Changes-Issues#15]
Glorious E lightweight armored mask dont have "repair cost" (bug) and "Material Type" bugget (must be aramid).

https://puu.sh/JdrOY/146f5c48c5.png

**Comment by VeryGooDiS** [comment]
DevTac Ronin ballistic helmet - same problem

https://tarkov-changes.com/item/DevTac%20Ronin%20ballistic%20helmet

**Comment by LogicalSoIutions** [comment]
This is correct information - this data is attached to the items profile 
![image](https://user-images.githubusercontent.com/67069181/181632214-26f237f5-ef06-45eb-a5de-f1ade5a0df22.png)

**Comment by VeryGooDiS** [comment]
What about repair cost?)

**Comment by VeryGooDiS** [comment]
> This is correct information - this data is attached to the items profile ![image](https://user-images.githubusercontent.com/67069181/181632214-26f237f5-ef06-45eb-a5de-f1ade5a0df22.png)


What about repair cost?)
