### ISSUE TITLE
Jack-o'-lantern tactical pumpkin helmet dont open

### ISSUE THREAD

**Issue by VeryGooDiS** [illogicalNetwork/Tarkov-Changes-Issues#16]
Have error "An error occurred, please try again. If the issue persists please contact us at [staff@illogical.network](mailto:staff@illogical.network)."

https://tarkov-changes.com/item/Jack-o-lantern%20tactical%20pumpkin%20helmet

**Comment by LogicalSoIutions** [comment]
Fixed on staging, going love shortly
