### ISSUE TITLE
Black keycard has incorrect item name

### ISSUE THREAD

**Issue by ckhawks** [illogicalNetwork/Tarkov-Changes-Issues#3]
http://tarkov-changes.com/item/keycard_black 

![image](https://user-images.githubusercontent.com/4939600/145880923-2611d3b8-f3e4-4ed4-815e-727bce86c588.png)

**Comment by LogicalSoIutions** [comment]
https://escapefromtarkov.fandom.com/wiki/Template:5751961824597720a31c09ac

This seems to be an old item that is no longer used. Will exclude this from search results.
