### ISSUE TITLE
Cases and containers are incorrectly categorized

### ISSUE THREAD

**Issue by ckhawks** [illogicalNetwork/Tarkov-Changes-Issues#5]
New containers (Injector Case and Keycard holder case) are labelled as Barters, some containers are labelled as Containers, some are labelled as general (non-existing and Pistol case), and then the med case is labelled as Medical. Secure containers too

Things that should be listed as Containers
- Secure containers (alpha, beta, epsilon, gamma, kappa, boss, developer)
- Stash containers (Ammunition case, THICC items, Mag case, weapon case, money case, item case, grenade case, thicc weapons, pistol case, med case)
- Pouches (injector case, keycard holder case, sicc case, documents case, dogtag case)

![image](https://user-images.githubusercontent.com/4939600/145881189-a2d08b27-23a6-4a4e-802d-d2a8e316f38f.png)

**Comment by LogicalSoIutions** [comment]
Most cases fixed - pistol case still bugged
