### ISSUE TITLE
Feature Request: Search by item category

### ISSUE THREAD

**Issue by ckhawks** [illogicalNetwork/Tarkov-Changes-Issues#6]
Users should be able to search/filter by an item category (barters, containers, medical). This could possibly be accomplished similar to how Google search does their prefixed arguments. `group:medical` or `category:medical`, or even just a fuzzy search for the group itself.

**Comment by RatherLogical** [comment]
We will not be adding the ability to search in specific categories, but there will be an items page that allows you to browse all of the in-game items by category.
