### ISSUE TITLE
Feature Request: Items have search-able (hidden) aliases

### ISSUE THREAD

**Issue by ckhawks** [illogicalNetwork/Tarkov-Changes-Issues#9]
Users should be able to search for alternative names or aliases of items. These aliases would be added manually to items as necessary. For a usage example, I could search `cheese` and AI-2 would be returned as a result.

Potential aliases:
- AI-2: cheese, AI2
- I can't think of more immediately, guess that means there wouldn't be too many lol

**Comment by RatherLogical** [comment]
I don't see this as really necessary, especially considering there are really not any aliases.
